//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc3839_24522
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int empid { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> department { get; set; }
        public Nullable<int> country { get; set; }
        public Nullable<int> state { get; set; }
    }
}
